version = 0.1
[default.deploy.parameters]
stack_name = "social-media"
s3_prefix = "social-media"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false
