version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::132260253285:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-12KT4ZX6NK9H3"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::132260253285:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-KM4VX34AWOSE"
cloudformation_execution_role = "arn:aws:iam::132260253285:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-HL93I66YDNUS"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1cguh8qv3823m"
image_repository = ""
region = "us-east-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::132260253285:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-9RUAM3K9C6BI"
cloudformation_execution_role = "arn:aws:iam::132260253285:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1FBF3YRXWBXUA"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1sxc8l0fkrr14"
image_repository = ""
region = "us-east-1"
